spring:
  application:
    name: PRODUCT-MANAGEMENT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dark
    username: root
    password: root
    hikari:
      connection-timeout: 60000
      max-lifetime: 100000
      leak-detection-threshold: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /product-management
